[env]
GOBIN = "{{ config_root }}/bin"
_.path = ["bin"]

[tools]
"ubi:abhinav/doc2go" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"ubi:miniscruff/changie" = "latest"
go = "latest"
node = "lts"

[tasks.build]
run = "go build ./..."
description = "Build the project"

[tasks.test]
description = "Run tests"
run = "go test -race ./..."

[tasks.cover]
description = "Run tests with coverage"
run = [
    "go test -race -coverprofile=cover.out -coverpkg=./... ./...",
    "go tool cover -html=cover.out -o cover.html"
]

[tasks.lint]
description = "Run all linters"
depends = ["lint:*"]

[tasks."lint:tidy"]
description = "Ensure go.mod is tidy"
run = "go mod tidy -diff"

[tasks."lint:golangci"]
description = "Run golangci-lint"
run = "golangci-lint run"

[tasks."lint:generate"]
description = "Verify generated code is up-to-date"
depends = ["generate"]
run = "git diff --exit-code"

[tasks.generate]
description = "Run all code generators"
depends = ["tools"]
run = "go generate ./..."

[tasks.tools]
run = "go install tool"
