// Code generated by "stringer -type RenderMode -trimprefix RenderMode"; DO NOT EDIT.

package mermaid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RenderModeAuto-0]
	_ = x[RenderModeClient-1]
	_ = x[RenderModeServer-2]
}

const _RenderMode_name = "AutoClientServer"

var _RenderMode_index = [...]uint8{0, 4, 10, 16}

func (i RenderMode) String() string {
	if i < 0 || i >= RenderMode(len(_RenderMode_index)-1) {
		return "RenderMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RenderMode_name[_RenderMode_index[i]:_RenderMode_index[i+1]]
}
