// Package svgtest includes helpers for validating SVGs in tests.
package svgtest

import (
	"regexp"
	"strings"
)

var _numberRe = regexp.MustCompile(`\d+(\.\d+)?`)

// Normalize normalizes SVGs generated by the CLI or CDP compilers.
//
// This is a hack.
// For some reason, the numbers in the SVGs generated by the CLI and CDP compilers
// differ on different machines.
//
// We fix those numbers to be 0 since the actual numbers matter less
// than the fact that the SVGs are roughly the same shape.
func Normalize(s string) string {
	s = _numberRe.ReplaceAllString(s, `0`)
	return strings.TrimSuffix(s, "\n")
}
