name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.18.x", "1.19.x"]
        include:
        - go: 1.19.x
          latest: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Lint
      if: matrix.latest
      run: make lint

    - name: Test
      run: make cover

    - name: Upload coverage
      uses: codecov/codecov-action@v1
