name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]
        include:
        - go: 1.20.x
          latest: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Download dependencies
      run: |
        go mod download
        yarn install

    - name: Build
      run: make build

    - name: Lint
      if: matrix.latest
      run: make lint

    - name: Test
      run: make cover

    - name: Upload coverage
      uses: codecov/codecov-action@v3
